module.exports = {
  // generic
  LANGUAGE_CODE_LENGTH: 2, // ISO-639-1

  // currency
  CURRENCY_CODE_LENGTH: 3, // ISO 4217 currency codes
  CURRENCY_AMOUNT_MINIMUM: 0,
  CURRENCY_MAX_PRECISION: 8,

  // user schema
  USER_FIRST_NAME_MIN_LENGTH: 2,
  USER_FIRST_NAME_MAX_LENGTH: 50,
  USER_LAST_NAME_MIN_LENGTH: 2,
  USER_LAST_NAME_MAX_LENGTH: 50,
  USER_EMAIL_MAX_LENGTH: 50,
  USER_PASSWORD_MIN_LENGTH: 8,
  USER_PASSWORD_MAX_LENGTH: 60,
  USER_PASSWORD_REGEX: new RegExp(
    "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])[a-zA-Z0-9]{8,60}$" // MIN AND MAX LENGTH HERE TOO
  ),

  // teacher schema
  TEACHER_DISPLAYNAME_MIN_LENGTH: 2,
  TEACHER_DISPLAYNAME_MAX_LENGTH: 20,
};
