module.exports = {
  // generic
  LANGUAGE_CODE_LENGTH: 2, // ISO-639-1

  // currency
  CURRENCY_CODE_LENGTH: 3, // ISO 4217 currency codes
  CURRENCY_AMOUNT_MINIMUM: 0,
  CURRENCY_MAX_PRECISION: 8,

  // user schema
  USER_FIRST_NAME_MIN_LENGTH: 2,
  USER_FIRST_NAME_MAX_LENGTH: 50,
  USER_LAST_NAME_MIN_LENGTH: 2,
  USER_LAST_NAME_MAX_LENGTH: 50,
  USER_EMAIL_MAX_LENGTH: 50,

  // teacher schema
  TEACHER_DISPLAYNAME_MIN_LENGTH: 4,
  TEACHER_DISPLAYNAME_MAX_LENGTH: 20,
};
